from .clusters_extaction import ClustersExtractionTask
from .clusters_footprint_analysis import ClustersFootprintAnalyzingTask
from .clusters_unification import ClustersUnificationTask
from .data_preview import DataPreviewTask
from .merger_task import MergerTask
from .score_assigning_task import ScoreAssigningTask
